adiciona protocolos
pythonbrasil/pybr2022-org pull request #318
Opened 2022-10-13 23:52 UTC by anicelysantos

2022-10-18 21:57 UTC, rougeth requested changes

2022-10-18 21:57 UTC, rougeth commented on protocolos/resposta-incidente-cdc.md
> +Se uma pessoa infratora quiser apelar da decisão, notifique-a de que ela pode entrar em contato com a APyB contato@python.org.br ou Python Brasil cdc@python.org.br.
Comentário acima sobre o e-mail.

2022-10-18 22:35 UTC, anicelysantos commented on protocolos/protocolo-denuncia-incidente.md
> + - E-mail cdc@python.org.br
Eu acho ótimo!

2022-10-27 18:06 UTC, rougeth approved these changes

2022-10-27 18:06 UTC, merged